let paises = [
  { name: 'Afganistán', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Albania', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Alemania', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Andorra', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Angola', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Antigua y Barbuda', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Arabia Saudita', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Argelia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Argentina', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Armenia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Australia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Austria', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Azerbaiyán', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bahamas', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bahrein', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bangladesh', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Barbados', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Belarús', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bélgica', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Benin', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bhután', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bolivia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bosnia y Herzegovina', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Botswana', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Brasil', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Brunei Darussalam', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bulgaria', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Burkina Faso', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Burundi', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Cabo Verde', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Camboya', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Camerún', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Canadá', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Chad', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Chile', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'China', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Chipre', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Colombia', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Comoras', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Congo', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Costa Rica', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Costa de Marfil', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Croacia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Cuba', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Dinamarca', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Djibouti', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Dominica', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Ecuador', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Egipto', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'El Salvador', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Emiratos Árabes Unidos', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Eritrea', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Eslovaquia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Eslovenia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'España', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Estados Unidos de América', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Estonia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Etiopía', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Ex República Yugoslava de Macedonia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Federación de Rusia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Fiji', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Filipinas', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Finlandia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Francia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Gabón', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Gambia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Georgia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Ghana', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Granada', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Grecia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guatemala', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guinea', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guinea Ecuatorial', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guinea-Bissau', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guyana', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Haití', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Honduras', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Hungría', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'India', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Indonesia', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Irán', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Iraq', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Irlanda', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Islandia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Islas Marshall', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Islas Salomón', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Israel', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Italia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Jamaica', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Japón', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Jordania', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kazajstán', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kenya', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kirguistán', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kiribati', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kuwait', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Lesotho', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Letonia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Líbano', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Liberia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Libia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Liechtenstein', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Lituania', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Luxemburgo', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Madagascar', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Malasia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Malawi', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Maldivas', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mali', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Malta', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Marruecos', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mauricio', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mauritania', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'México', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Micronesia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mónaco', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mongolia', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Montenegro', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mozambique', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Myanmar', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Namibia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nauru', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nepal', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nicaragua', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Niger', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nigeria', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Noruega', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nueva Zelanda', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Omán', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Países Bajos', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Pakistán', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Palau', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Panamá', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Papua Nueva Guinea', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Paraguay', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Perú', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Polonia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Portugal', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Quatar', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Reino Unido de Gran Bretaña e Irlanda del Norte', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Árabe Siria', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Centroafricana', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Checa', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República de Corea', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República de Moldova', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Democrática del Congo', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Popular Democrática de Corea', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Dominicana', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Popular Democrática de Lao', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Unida de Tanzania', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Rumania', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Rwanda', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Saint Kitts y Nevis', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Samoa', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'San Marino', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'San Vicente y las Granadinas', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Santa Lucía', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Santo Tomé y Príncipe', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Senegal', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Serbia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Seychelles', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sierra Leona', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Singapur', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Somalía', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sri Lanka', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sudáfrica', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sudán', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sudán del Sur', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Suecia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Suiza', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Suriname', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Swazilandia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Tailandia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Tayikistán', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Timor-Leste', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Togo', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Tonga', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Trinidad y Tobago', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Túnez', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Turkmenistán', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Turquía', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Tuvalu', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Ucrania', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Uganda', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Uruguay', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Uzbekistán', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Vanatu', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Venezuela', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Viet Nam', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Yemen', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Zambia', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Zimbabwe', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'ZZ Banco Mundial', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'ZZ Comité Internacional de la Cruz Roja', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'ZZ Comunidad del Caribe', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'ZZ Fondo Monetario Internacional', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'ZZ Liga Árabe', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'ZZ Organización para la Unidad Africana', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'ZZ Palestina', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'ZZ Santa Sede', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'ZZ Secretaría del Commonwealth', participa: true, isPresent: true, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'ZZ Unión Europea', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true }
]

export default paises