let paises = [
  { name: 'Afganistán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Albania', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Alemania', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Andorra', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Angola', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Antigua y Barbuda', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Arabia Saudita', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Argelia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Argentina', participa: true, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Armenia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Australia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Austria', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Azerbaiyán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bahamas', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bahrein', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bangladesh', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Barbados', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Belarús', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bélgica', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Benin', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bhután', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bolivia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bosnia y Herzegovina', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Botswana', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Brasil', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Brunei Darussalam', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Bulgaria', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Burkina Faso', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Burundi', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Cabo Verde', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Camboya', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Camerún', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Canadá', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Chad', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Chile', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'China', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Chipre', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Colombia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Comoras', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Congo', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Costa Rica', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Costa de Marfil', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Croacia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Cuba', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Dinamarca', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Djibouti', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Dominica', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Ecuador', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Egipto', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'El Salvador', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Emiratos Árabes Unidos', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Eritrea', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Eslovaquia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Eslovenia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'España', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Estados Unidos de América', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Estonia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Etiopía', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Ex República Yugoslava de Macedonia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Federación de Rusia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Fiji', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Filipinas', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Finlandia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Francia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Gabón', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Gambia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Georgia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Ghana', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Granada', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Grecia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guatemala', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guinea', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guinea Ecuatorial', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guinea-Bissau', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Guyana', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Haití', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Honduras', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Hungría', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'India', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Indonesia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Irán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Iraq', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Irlanda', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Islandia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Islas Marshall', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Islas Salomón', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Israel', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Italia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Jamaica', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Japón', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Jordania', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kazajstán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kenya', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kirguistán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kiribati', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Kuwait', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Lesotho', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Letonia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Líbano', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Liberia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Libia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Liechtenstein', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Lituania', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Luxemburgo', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Madagascar', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Malasia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Malawi', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Maldivas', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mali', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Malta', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Marruecos', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mauricio', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mauritania', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'México', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Micronesia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mónaco', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mongolia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Montenegro', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Mozambique', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Myanmar', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Namibia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nauru', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nepal', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nicaragua', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Niger', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nigeria', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Noruega', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Nueva Zelanda', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Omán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Países Bajos', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Pakistán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Palau', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Panamá', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Papua Nueva Guinea', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Paraguay', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Perú', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Polonia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Portugal', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Quatar', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Reino Unido de Gran Bretaña e Irlanda del Norte', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Árabe Siria', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Centroafricana', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Checa', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República de Corea', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República de Moldova', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Democrática del Congo', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Popular Democrática de Corea', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Dominicana', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Popular Democrática de Lao', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'República Unida de Tanzania', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Rumania', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Rwanda', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Saint Kitts y Nevis', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Samoa', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'San Marino', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'San Vicente y las Granadinas', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Santa Lucía', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Santo Tomé y Príncipe', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Senegal', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Serbia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Seychelles', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sierra Leona', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Singapur', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Somalía', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sri Lanka', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sudáfrica', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sudán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Sudán del Sur', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Suecia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Suiza', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Suriname', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Swazilandia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Tailandia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Tayikistán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Timor-Leste', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Togo', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Tonga', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Trinidad y Tobago', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Túnez', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Turkmenistán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Turquía', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Tuvalu', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Ucrania', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Uganda', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Uruguay', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Uzbekistán', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Vanatu', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Venezuela', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Viet Nam', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Yemen', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Zambia', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Zimbabwe', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: false },
  { name: 'Banco Mundial', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'Comité Internacional de la Cruz Roja', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'Comunidad del Caribe', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'Fondo Monetario Internacional', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'Liga Árabe', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'Organización para la Unidad Africana', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'Palestina', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'Santa Sede', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'Secretaría del Commonwealth', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true },
  { name: 'Unión Europea', participa: false, isPresent: false, questions: 0, answers: 0, motions: 0, speech: 0, observer: true }
]

export default paises